#pragma once

enum {
	READ_COILS_FC = 1,
	READ_DISCRETE_INPUTS_FC,
	READ_HOLDING_REGISTERS_FC,
	READ_INPUT_REGISTER_FC,
	WRITE_SINGLE_COIL_FC,
	WRITE_SINGLE_REGISTER_FC,
	READ_EXCEPTION_STATUS_FC,
	DIAGNOSTIC_FC,
	END_FC
}MODBUS_FUNCTION_CODE;